[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ma_thesis"
version = "0.0.1"
description = "MA Thesis"
authors = [
  { name = "Adam Korba" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "flax>=0.10.7",
    "jax>=0.6.2",
    "loguru",
    "marimo>=0.18.1",
    "matplotlib>=3.10.7",
    "mlflow>=2.12",
    "mkdocs",
    "numpy>=2.2.6",
    "openai>=2.9.0",
    "pip",
    "polars>=1.36.1",
    "python-dotenv",
    "ruff",
    "tqdm",
    "typer",
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["ma_thesis"]
include = ["pyproject.toml", "ma_thesis/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["ma_thesis"]
force-sort-within-sections = true

