run:
  method: sweep
  function: friedman2_2d
  regenerate_data: true
  num_samples: 20000
  num_sigmas: 3
  sigma_scale: 5.0
  train_samples: 10000
  noise_ratio: 0.02
  seed: 42
  experiment_name: sweep-friedman2-2d-v2-ratio
  sweep_storage: sqlite:///reports/optuna/sweep_friedman2_2d_v2_ratio.db
  n_trials: 90
  epochs: 900
  patience: 25
  min_delta: 0.00001
  report_interval: 10
  grid_res: 90
  model_archs: "mlp,siren,fourier"
  min_train_per_param: 10.0
  max_train_per_param: 20.0
